// Generated by CoffeeScript 1.7.1
var dictionary, directory, shiori;

self.importScripts("node_modules/ikagaka.nar.js/node_modules/encoding-japanese/encoding.js");

self.importScripts("node_modules/shiorijk/lib/shiorijk.js");

self.importScripts("node_modules/miyojs-filter-autotalks/autotalks.js");

self.importScripts("node_modules/miyojs-filter-default_response_headers/default_response_headers.js");

self.importScripts("node_modules/miyojs-filter-property/property.js");

self.importScripts("node_modules/miyojs-filter-variables/variables.js");

self.importScripts("node_modules/miyojs-filter-value_filters/value_filters.js");

self.importScripts("node_modules/miyojs/node_modules/js-yaml/dist/js-yaml.min.js");

self.importScripts("node_modules/miyojs/lib/miyo.js");

directory = null;

dictionary = null;

shiori = null;

self.onmessage = function(_arg) {
  var data, event, paser, request, requestTxt, response, responseTxt, _ref;
  _ref = _arg.data, event = _ref.event, data = _ref.data;
  switch (event) {
    case "load":
      directory = data;
      dictionary = Object.keys(directory["dictionaries"]).reduce((function(dictionary, filename) {
        var dic, err, yaml;
        if (directory["dictionaries"][filename] instanceof ArrayBuffer) {
          yaml = Encoding.codeToString(Encoding.convert(new Uint8Array(directory["dictionaries"][filename]), 'UNICODE', 'AUTO')).replace(/\t/g, ' ');
          try {
            dic = jsyaml.safeLoad(yaml);
            Miyo.DictionaryLoader.merge_dictionary(dic, dictionary);
          } catch (_error) {
            err = _error;
            console.log(err);
          }
        }
        return dictionary;
      }), {});
      shiori = new Miyo(dictionary);
      shiori.load({});
      console.log(shiori);
      return self.postMessage({
        "event": "loaded",
        "error": null
      });
    case "request":
      requestTxt = data;
      paser = new ShioriJK.Shiori.Request.Parser();
      request = paser.parse(requestTxt);
      console.log(request);
      response = shiori.request(request);
      console.log(response);
      responseTxt = "" + response;
      return self.postMessage({
        event: "response",
        error: null,
        data: responseTxt
      });
    case "unload":
      shiori.unload();
      return self.postMessage({
        event: "unloaded",
        error: null
      });
    default:
      throw new Error(event + " event not support");
  }
};
