// Generated by CoffeeScript 1.7.1
var Shiori, shiori;

self.importScripts("node_modules/shiorijk/lib/shiorijk.js");

self.importScripts("node_modules/miyojs/lib/miyo.js");

Shiori = (function() {
  function Shiori() {
    this.directory = null;
  }

  Shiori.prototype.load = function(directory, callback) {
    this.directory = directory;
    return setTimeout(function() {
      return callback(null);
    });
  };

  Shiori.prototype.request = function(request, callback) {
    return setTimeout(function() {
      return callback(null, "hello");
    });
  };

  Shiori.prototype.unload = function(callback) {
    return setTimeout(function() {
      return callback(null);
    });
  };

  return Shiori;

})();

shiori = new Shiori();

self.onmessage = function(_arg) {
  var data, event, _ref;
  _ref = _arg.data, event = _ref.event, data = _ref.data;
  switch (event) {
    case "load":
      return shiori.load(data, function(err) {
        return self.postMessage({
          event: "loaded",
          error: err
        });
      });
    case "request":
      return shiori.request(data, function(err, response) {
        return self.postMessage({
          event: "response",
          error: err,
          data: response
        });
      });
    case "unload":
      return shiori.unload(function(err) {
        return self.postMessage({
          event: "unloaded",
          error: err
        });
      });
  }
};
