// Generated by CoffeeScript 1.9.1
(function() {
  var Ghost;

  Ghost = (function() {
    Ghost.shiori_detectors = [];

    Ghost.shiories = {};

    function Ghost(fs) {
      var i, len, ref, shiori_detector, shiori_name;
      ref = Ghost.shiori_detectors;
      for (i = 0, len = ref.length; i < len; i++) {
        shiori_detector = ref[i];
        if (shiori_detector.detect(fs)) {
          shiori_name = shiori_detector.name;
          break;
        }
      }
      if (shiori_name == null) {
        throw new Error("shiori not found or unknown shiori");
      }
      this.shiori = new Ghost.shiories[shiori_name](fs);
    }

    Ghost.prototype.load = function(dirpath) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return resolve(_this.shiori.load(dirpath));
        };
      })(this));
    };

    Ghost.prototype.request = function(request) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return resolve(_this.shiori.request(request));
        };
      })(this));
    };

    Ghost.prototype.unload = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return resolve(_this.shiori.unload());
        };
      })(this));
    };

    return Ghost;

  })();

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = Ghost;
  } else if (this.Ikagaka != null) {
    this.Ikagaka.Ghost = Ghost;
  } else {
    this.Ghost = Ghost;
  }

}).call(this);
